# pubspec.yaml
name: vifosa
description: Viet Food Shops Alliance — đặt đồ ăn TPHCM
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Location
  geolocator: ^12.0.0

  # State management
  flutter_riverpod: ^2.5.1

  # HTTP client
  dio: ^5.4.3
  http: ^1.2.0

  # Navigation
  go_router: ^13.2.0

  # Secure token storage (JWT)
  flutter_secure_storage: ^9.2.2

  # Image loading & cache
  cached_network_image: ^3.3.1

  # Image picker (upload ảnh món, avatar, post)
  image_picker: ^1.1.2

  # Image compress trước upload
  flutter_image_compress: ^2.2.0

  # Firebase FCM
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19

  # Local storage
  shared_preferences: ^2.2.0
  hive_flutter: ^1.1.0

  # Map OSM
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Real-time
  socket_io_client: ^2.0.3+1

  # Utility
  intl: ^0.19.0
  url_launcher: ^6.2.5
  share_plus: ^9.0.0
  qr_flutter: ^4.1.0
  permission_handler: ^11.3.1
  image: ^4.8.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
# pubspec.yaml